os:
  - linux

language: cpp

before_install:
  - sudo apt-get install -y libssl-dev
  - autoreconf -i

before_script:
  - autoreconf -i

script: "./configure --enable-openssl --disable-silent-rules && make && make check"